#!/bin/bash

set -eu

# include Silver bash library functions `set_readlink` and
# `setup_syn_link`
source ~/bin/silver-bash-lib.sh
set_readlink


if [ ! -d jars ]; then
  mkdir -p jars
fi

if [ ! -d generated ]; then
  mkdir -p generated
fi

# Build treesitter conflicts library
echo "Building Treesitter conflicts jar"
cd TreesitterConflicts
javac Main.java
jar cfm TreesitterConflicts.jar manifest.txt *.class
mv TreesitterConflicts.jar ../jars/
cd ..
echo "Built Treesitter conflicts jar"

# Set up symbolic links
setup_sym_link $(pwd)/scripts/gen-treesitter-parser ~/bin/gen-treesitter-parser
setup_sym_link $(pwd)/scripts/slide ~/bin/slide
setup_sym_link $(pwd)/scripts/gen-atom-language-package ~/bin/gen-atom-language-package
setup_sym_link $(pwd)/scripts/gen-atom-lsp-package ~/bin/gen-atom-lsp-package
setup_sym_link $(pwd)/scripts/hook-into-genericLanguageServer ~/bin/hook-into-genericLanguageServer
setup_sym_link $(pwd)/melt-atom-light-syntax ~/.atom/packages/melt-atom-light-syntax

echo "Building slide"
cd slide
./self-compile
cd ..
echo "Slide built"
