#!/bin/bash

set -eu

if [ ! -d jars ]; then
  mkdir -p jars
fi

if [ ! -d generated ]; then
  mkdir -p generated
fi

# Build treesitter conflicts library
echo "Building Treesitter conflicts jar"
cd TreesitterConflicts
javac Main.java
jar cfm TreesitterConflicts.jar manifest.txt *.class
mv TreesitterConflicts.jar ../jars/
cd ..
echo "Built Treesitter conflicts jar"

# Set up symbolic links
if [ ! -f ~/bin/gen-treesitter-parser ]; then
  ln -s $(pwd)/scripts/gen-treesitter-parser ~/bin/gen-treesitter-parser
  echo "Symbolic link for gen-treesitter-parser script set up"
fi

if [ ! -f ~/bin/slide ]; then
  ln -s $(pwd)/scripts/slide ~/bin/slide
  echo "Symbolic link for slide set up"
fi

if [ ! -f ~/bin/gen-atom-language-package ]; then
  ln -s $(pwd)/scripts/gen-atom-language-package ~/bin/gen-atom-language-package
  echo "Symbolic link for gen-atom-language-package script set up"
fi

if [ ! -f ~/bin/gen-atom-lsp-package ]; then
  ln -s $(pwd)/scripts/gen-atom-lsp-package ~/bin/gen-atom-lsp-package
  echo "Symbolic link for gen-atom-lsp-package script set up"
fi

if [ ! -f ~/bin/hook-into-genericLanguageServer ]; then
  ln -s $(pwd)/scripts/hook-into-genericLanguageServer ~/bin/hook-into-genericLanguageServer
  echo "Symbolic link for hook-into-genericLanguageServer script set up"
fi

# set up a symbolic link so Atom finds our highlighting theme
if [ ! -f ~/.atom/packages/melt-atom-light-syntax ]; then
  echo "Adding MELT light demo theme to Atom packages"
  ln -s $(pwd)/melt-atom-light-syntax ~/.atom/packages/melt-atom-light-syntax
  echo "Added MELT light demo theme to Atom packages"
fi

echo "Building slide"
cd slide
./self-compile
cd ..
echo "Slide built"
