#!/bin/bash

case `uname` in
*Darwin*)
  READLINK=greadlink
  if [ ! -f `which greadlink` ]; then
    echo "Missing greadlink. Please install coreutils:"
    echo -e "\tbrew install coreutils"
    exit 4
  fi
  ;;
*)
  READLINK=readlink
  ;;
esac

# ~/bin/silver-ide should be a link to somewhere, find out where!
ME=$(${READLINK} -f "${BASH_SOURCE}")
# Set our home
export SILVER_IDE_HOME=${ME/scripts\/slide/}
COMPILER_JAR="jars/slide.compiler.jar"
SLIDE="$SILVER_IDE_HOME$COMPILER_JAR"

if [ ! -f "$SILVER_IDE" ]; then
  echo "Couldn't find the Slide jars to execute, aborting."
  exit 2
fi

java -jar "$SLIDE" "$@"
